---
apiVersion: source.toolkit.fluxcd.io/v1
kind: OCIRepository
metadata:
  name: amd-gpu-dra-driver
spec:
  interval: 15m
  layerSelector:
    mediaType: application/vnd.cncf.helm.chart.content.v1.tar+gzip
    operation: copy
  ref:
    tag: 1.0.1
    digest: sha256:3435d7adebcda6489f6ee7df29c0bf7a239772f9f1256ebeca3b40432d619385
  url: oci://ghcr.io/home-operations/charts-mirror/k8s-gpu-dra-driver
