---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loopdedupe-search-api-key
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p-tf
  refreshInterval: "30m"
  target:
    name: loopdedupe-search-api-key
  data:
    - secretKey: search
      remoteRef:
        key: LOOPDEDUPE_SEARCH_API_KEY
