---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: loopdedupe-oidc
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p-tf
  refreshInterval: "30m"
  target:
    name: loopdedupe-oidc
  data:
    - secretKey: client-id
      remoteRef:
        key: ZITADEL_OAUTH_CLIENT_ID_LOOPDEDUPE
    - secretKey: client-secret
      remoteRef:
        key: ZITADEL_OAUTH_CLIENT_SECRET_LOOPDEDUPE
