---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./ocirepository.yaml
  - ./secrets.yaml
  - ./docker-config.yaml
  - ./runners.yaml
  - ./bucket.yaml
  - ./pdb.yaml
