apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-app-runner-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p-tf
  refreshInterval: "1h"
  data:
    - secretKey: github_app_id
      remoteRef:
        key: GITHUB_APP_IMMICH_SELFHOSTED_RUNNERS
        property: app_id
    - secretKey: github_app_installation_id
      remoteRef:
        key: GITHUB_APP_IMMICH_SELFHOSTED_RUNNERS
        property: installation_id
    - secretKey: github_app_private_key
      remoteRef:
        key: GITHUB_APP_IMMICH_SELFHOSTED_RUNNERS
        property: pkcs1
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: futo-org-runner-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p-tf
  refreshInterval: "1h"
  data:
    - secretKey: github_app_id
      remoteRef:
        key: GITHUB_APP_IMMICH_SELFHOSTED_RUNNERS
        property: app_id
    - secretKey: github_app_installation_id
      remoteRef:
        key: GITHUB_APP_FUTO_ORG_SELFHOSTED_RUNNERS_INSTALLATION_ID
    - secretKey: github_app_private_key
      remoteRef:
        key: GITHUB_APP_IMMICH_SELFHOSTED_RUNNERS
        property: pkcs1
