apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actions-controller-github-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p-kubernetes
  refreshInterval: "1h"
  dataFrom:
    - extract:
        key: actions-controller-github-auth
