apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: actions-controller-github-auth
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p-kubernetes
  refreshInterval: "1h"
  data:
    - secretKey: github_app_id
      remoteRef:
        key: actions-controller-github-auth
        property: github_app_id
    - secretKey: github_app_installation_id
      remoteRef:
        key: actions-controller-github-auth
        property: github_app_installation_id
    - secretKey: github_app_private_key
      remoteRef:
        key: actions-controller-github-auth
        property: github_app_private_key
