[tools]
talosctl = "1.13.3"
talhelper = "3.1.10"
kubectl = "1.36.1"
helmfile = "1.5.2"
helm = "3.21.0"
usage = "3.3.0"
flux2 = "2.7.3"

[tasks."talos:genconfig"]
dir = "talos"
run = "talhelper genconfig --secret-file <(op inject -i talsecret.yaml)"
outputs = ["talos/clusterconfig"]

[tasks."talos:apply"]
dir = "talos"
depends = ["talos:genconfig"]
confirm = "Are you sure you want to apply the talos config to all nodes?"
run = "talhelper gencommand apply | bash"

[tasks."talos:bootstrap-k8s"]
dir = "talos"
depends = ["talos:genconfig"]
run = """
KUBECONFIG=$(mktemp)
trap 'rm -f "$KUBECONFIG"' EXIT
talhelper gencommand kubeconfig --extra-flags - | bash > "$KUBECONFIG"
helmfile --kubeconfig "$KUBECONFIG" --file '{{ config_root }}/bootstrap/helmfile.yaml' sync
"""
