---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: onepassword
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: onepassword
  values:
    connect:
      credentialsName: onepassword-api
      credentialsKey: session
      serviceType: ClusterIP
    operator:
      create: false
