---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/infrastructure/secrets/external-secrets/app
  prune: true
  targetNamespace: secrets
  dependsOn:
    - name: onepassword
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: external-secrets
      namespace: secrets
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-stores
  namespace: flux-system
spec:
  interval: 1h
  path: ./kubernetes/apps/infrastructure/secrets/external-secrets/stores
  prune: true
  targetNamespace: secrets
  dependsOn:
    - name: external-secrets
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
