---
apiVersion: resource.k8s.io/v1
kind: DeviceClass
metadata:
  name: dgpu-nvidia-ampere
spec:
  selectors:
    - cel:
        expression: device.driver == 'gpu.nvidia.com' && device.attributes['gpu.nvidia.com'].architecture == 'Ampere'
