---
machine:
  type: worker
  install:
    diskSelector:
      type: nvme
    image: factory.talos.dev/metal-installer/759b2b21175fec663f0a9559999d094ba661fe0687e45aac674c944a871ac652:v1.14.1
---
apiVersion: v1alpha1
kind: HostnameConfig
auto: 'off'
hostname: eevee
