---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway
spec:
  interval: 1h
  path: ./kubernetes/apps/infrastructure/network/envoy-gateway/app
  prune: true
  targetNamespace: network
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: envoy-gateway
      namespace: network
  wait: true
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: envoy-gateway-config
spec:
  interval: 1h
  path: ./kubernetes/apps/infrastructure/network/envoy-gateway/config
  prune: true
  targetNamespace: network
  dependsOn:
    - name: envoy-gateway
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  wait: true
