---
version: v1alpha1
debug: false
persist: true
machine:
  features:
    diskQuotaSupport: true
---
apiVersion: v1alpha1
kind: KubeClusterConfig
clusterName: pokedex
endpoint: https://kube.pokedex.internal.immich.cloud:6443
---
apiVersion: v1alpha1
kind: KubeNetworkConfig
dnsDomain: cluster.local
podSubnets:
  - 10.244.0.0/16
serviceSubnets:
  - 10.96.0.0/12
---
apiVersion: v1alpha1
kind: DiscoveryServiceConfig
name: default
endpoint: https://discovery.talos.dev/
---
apiVersion: v1alpha1
kind: ResolverConfig
hostDNS:
  enabled: true
  forwardKubeDNSToHost: true
---
apiVersion: v1alpha1
kind: KubePrismConfig
port: 7445
---
apiVersion: v1alpha1
kind: KubeletConfig
image: ghcr.io/siderolabs/kubelet:v1.37.0
defaultRuntimeSeccompProfileEnabled: true
