---
clusterName: pokedex

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://kube.pokedex.internal.immich.cloud:6443
certSANs:
  - kube.pokedex.internal.immich.cloud
allowSchedulingOnControlPlanes: true

cniConfig:
  name: none

controlPlane:
  patches:
    - |-
      machine:
        network:
          interfaces:
            - interface: bond0
              routes:
                - network: 0.0.0.0/0
                  gateway: 10.10.10.1
    - |-
      cluster:
        proxy:
          disabled: true
    - |-
      machine:
        features:
          kubernetesTalosAPIAccess:
            enabled: true
            allowedKubernetesNamespaces:
              - system-upgrade
            allowedRoles:
              - os:admin
nodes:
  - hostname: brock
    controlPlane: true
    ipAddress: 10.10.10.11
    installDiskSelector:
      size: '>= 1TB'
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/amdgpu
            - siderolabs/nonfree-kmod-nvidia-lts
            - siderolabs/nvidia-container-toolkit-lts
    patches:
      - |-
        machine:
          kernel:
            modules:
              - name: nvidia
              - name: nvidia_uvm
              - name: nvidia_drm
              - name: nvidia_modeset
    networkInterfaces:
      - interface: bond0
        addresses:
          - 10.10.10.11/24
        bond:
          mode: active-backup
          deviceSelectors:
            - permanentAddr: '08:c0:eb:0a:14:91'
            - permanentAddr: '08:c0:eb:0a:14:90'
      - deviceSelector:
          permanentAddr: 'd0:50:99:c3:36:35'
        ignore: true
  - hostname: surge
    controlPlane: true
    ipAddress: 10.10.10.12
    installDiskSelector:
      size: '>= 1TB'
      wwid: 'naa.500a075121a495a7'
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
            - siderolabs/nvidia-open-gpu-kernel-modules-production
            - siderolabs/nvidia-container-toolkit-production
    patches:
      - |-
        machine:
          kernel:
            modules:
              - name: nvidia
              - name: nvidia_uvm
              - name: nvidia_drm
              - name: nvidia_modeset
    networkInterfaces:
      - interface: bond0
        addresses:
          - 10.10.10.12/24
        bond:
          mode: active-backup
          deviceSelectors:
            - permanentAddr: '1c:34:da:0c:d2:b1'
            - permanentAddr: '1c:34:da:0c:d2:b0'
      - deviceSelector:
          permanentAddr: 'd0:50:99:c3:36:4b'
        ignore: true
  - hostname: misty
    controlPlane: true
    ipAddress: 10.10.10.13
    installDiskSelector:
      size: '>= 1TB'
      wwid: 'naa.500117310012436c'
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
    networkInterfaces:
      - interface: bond0
        addresses:
          - 10.10.10.13/24
        bond:
          mode: active-backup
          deviceSelectors:
            - permanentAddr: 'e4:43:4b:18:3a:00'
            - permanentAddr: 'e4:43:4b:18:3a:02'
  - hostname: vaporeon
    ipAddress: 10.10.10.200
    installDiskSelector:
      type: nvme
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/amdgpu
  - hostname: bulbasaur
    ipAddress: 10.10.10.176
    installDiskSelector:
      type: nvme
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/amd-ucode
            - siderolabs/amdgpu
  - hostname: geodude
    ipAddress: 10.10.10.132
    installDiskSelector:
      type: nvme
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
  - hostname: sylveon
    ipAddress: 10.10.10.245
    installDiskSelector:
      type: ssd
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
  - hostname: eevee
    ipAddress: 10.10.10.222
    installDiskSelector:
      type: nvme
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
  - hostname: flareon
    ipAddress: 10.10.10.51
    installDiskSelector:
      type: ssd
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
  - hostname: magikarp
    ipAddress: 10.10.10.63
    installDiskSelector:
      type: ssd
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
  - hostname: pikachu
    ipAddress: 10.10.10.23
    installDiskSelector:
      type: nvme
    schematic:
      customization:
        systemExtensions:
          officialExtensions:
            - siderolabs/intel-ucode
