---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: vmagent-remote-write
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p-tf-prod
  refreshInterval: "30m"
  target:
    name: vmagent-remote-write
  data:
    - secretKey: token
      remoteRef:
        key: O11Y_VICTORIAMETRICS_VMAUTH_PASSWORD
