apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: containerssh-host-key
  namespace: tools
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p-kubernetes
  refreshInterval: "30m"
  data:
    - secretKey: host.key
      remoteRef:
        key: containerssh-host-key
        property: host.key
