apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: containerssh-oauth-clientid
  namespace: tools
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: 1p-tf
  refreshInterval: "30m"
  data:
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: FUTO_ZITADEL_OAUTH_CLIENT_ID_CONTAINERSSH
