---
apiVersion: postgresql.cnpg.io/v1
kind: Database
metadata:
  name: loopdedupe
spec:
  name: app
  owner: app
  cluster:
    name: loopdedupe
  extensions:
    - name: vector
      ensure: present
    - name: vchord
      ensure: present
