apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: amd-gpu-dra-driver
spec:
  interval: 1h
  path: ./kubernetes/apps/infrastructure/gpu/amd/app
  prune: true
  targetNamespace: gpu
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  healthChecks:
    - apiVersion: helm.toolkit.fluxcd.io/v2
      kind: HelmRelease
      name: amd-gpu-dra-driver
      namespace: gpu
  wait: true
